version: "3.2"

services:
  node-subtensor:
    container_name: node-subtensor
    image: opentensor/subtensor:latest
    cpu_count: 2
    mem_limit: 4000000000
    memswap_limit: 8000000000
    ports:
      - "9944:9944"
      - "30333:30333"
      - "9933:9933"
    expose:
      - "9944"
      - "30333"
      - "9933"
    environment:
      - CARGO_HOME=/var/www/node-subtensor/.cargo
    command: bash -c "./node-subtensor --base-path /root/.local/share/node-subtensor/ --chain finney --rpc-external --ws-external --rpc-cors all --no-mdns --ws-max-connections 10000 --in-peers 500 --out-peers 500"

