[toolchain]
channel = "1.89" # rustc 1.89.0 (29483883e 2025-08-04)
components = [
	"cargo",
	"clippy",
	"rust-analyzer",
	"rust-src",
	"rust-std",
	"rustc",
	"rustc-dev",
	"rustfmt",
]
targets = ["wasm32v1-none"]
profile = "minimal"
