[toolchain]
channel = "1.84.0"
components = [
	"cargo",
	"clippy",
	"rust-analyzer",
	"rust-src",
	"rust-std",
	"rustc",
	"rustc-dev",
	"rustfmt",
]
targets = ["wasm32-unknown-unknown"]
profile = "minimal"
