[package]
name = "stp-shield"
description = "MEV Shield primitives for Subtensor runtime"
version = "0.1.0"
edition.workspace = true


[dependencies]
codec.workspace = true
scale-info.workspace = true
sp-externalities.workspace = true
sp-api.workspace = true
sp-runtime.workspace = true

[lints]
workspace = true

[features]
default = ["std"]
std = ["codec/std", "sp-externalities/std", "sp-api/std", "sp-runtime/std"]
