[package]
name = "pallet-rate-limiting-runtime-api"
version = "0.1.0"
description = "Runtime API for the rate limiting pallet"
edition.workspace = true

[dependencies]
codec = { workspace = true, features = ["derive"] }
scale-info = { workspace = true, features = ["derive"] }
sp-api.workspace = true
sp-std.workspace = true
pallet-rate-limiting.workspace = true
subtensor-runtime-common = { workspace = true, default-features = false }
serde = { workspace = true, features = ["derive"], optional = true }
subtensor-macros.workspace = true

[features]
default = ["std"]
std = [
	"codec/std",
	"scale-info/std",
	"sp-api/std",
	"sp-std/std",
	"pallet-rate-limiting/std",
	"subtensor-runtime-common/std",
	"serde/std",
]
