[package]
name = "subtensor-linting"
version = "0.1.0"
edition.workspace = true

[dependencies]
syn = { workspace = true, features = [
    "full",
    "visit-mut",
    "visit",
    "extra-traits",
    "parsing",
] }
quote.workspace = true
proc-macro2.workspace = true
frame-support-procedural-core.workspace = true

[lints]
workspace = true
