[package]
name = "subtensor-custom-rpc"
version = "0.0.2"
edition = "2021"
authors = ['Cameron Fairchild <https://github.com/camfairchild>']
repository = 'https://github.com/opentensor/subtensor'
description = "A pallet that adds custom RPC calls to subtensor"
license = "MIT"
publish = false

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [
  "derive",
] }
jsonrpsee = { version = "0.16.2", features = [
  "client-core",
  "server",
  "macros",
], default-features = false }
serde = { version = "1.0.132", features = ["derive"], default-features = false }

# Substrate packages
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.39", default-features = false }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.39", default-features = false }
sp-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.39", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.39", default-features = false }

# local packages

subtensor-custom-rpc-runtime-api = { version = "0.0.2", path = "../runtime-api", default-features = false }
pallet-subtensor = { version = "4.0.0-dev", path = "../../subtensor", default-features = false }


[dev-dependencies]
# subtensor-custom-rpc-api = { version = "0.0.2", path = "../runtime-api", default-features = false }
substrate-test-runtime-client = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.39", default-features = false }
# sp_version = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.39", default-features = false }
# sp_core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.39", default-features = false }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.39", default-features = false }

tokio = { version = "1.24.1", features = ["macros", "time", "parking_lot"] }
# subtensor-custom-rpc-runtime = { version = "0.0.2", path = "../runtime", default-features = false }
# node-subtensor-runtime = { version = "4.0.0-dev", path = "../../runtime", default-features = false }


[features]
default = ["std"]
std = ["sp-api/std", "sp-runtime/std", "subtensor-custom-rpc-runtime-api/std"]
pow-faucet = []
subnet-staking = []
