[package]
name = "subtensor-swap-interface"
version = "0.1.0"
edition.workspace = true

[dependencies]
frame-support.workspace = true
substrate-fixed.workspace = true
subtensor-runtime-common.workspace = true

[lints]
workspace = true

[features]
default = ["std"]
std = [
	"frame-support/std",
	"substrate-fixed/std",
	"subtensor-runtime-common/std",
]
