[package]
name = "pallet-subtensor-swap-runtime-api"
version = "1.0.0"
description = "Runtime API for the Swap pallet"
edition.workspace = true

[dependencies]
frame-support.workspace = true
sp-api.workspace = true
subtensor-macros.workspace = true
subtensor-runtime-common = { workspace = true, default-features = false }

[features]
default = ["std"]
std = [
    "frame-support/std",
    "sp-api/std",
    "subtensor-runtime-common/std",
]
