[package]
name = "safe-math"
version = "0.1.0"
edition.workspace = true

[package.metadata.cargo-machete]
ignored = [
    "num-traits",              # Used in numeric trait features
    "sp-std"                   # Used in no-std features
]

[dependencies]
substrate-fixed.workspace = true
sp-arithmetic.workspace = true
sp-std.workspace = true
num-traits = { workspace = true, features = ["libm"] }

[lints]
workspace = true

[features]
default = ["std"]
std = [
	"substrate-fixed/std",
	"sp-std/std",
	"sp-arithmetic/std",
	"num-traits/std",
]
