[package]
name = "safe-math"
version = "0.1.0"
edition.workspace = true

[dependencies]
substrate-fixed.workspace = true
sp-arithmetic.workspace = true

[lints]
workspace = true

[features]
default = ["std"]
std = [
	"substrate-fixed/std",
	"sp-arithmetic/std",
]
