name: cargo audit
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
concurrency:
  group: cargo-audit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cargo-audit:
    name: cargo audit
    runs-on: SubtensorCI
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-cargo-audit') }}
    steps:
      - name: Check-out repositoroy under $GITHUB_WORKSPACE
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update &&
          sudo apt-get install -y clang curl libssl-dev llvm libudev-dev protobuf-compiler

      - name: Utilize Shared Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: cargo-audit
          cache-on-failure: true

      - name: Install cargo-audit
        run: cargo install --force cargo-audit

      - name: Display cargo-audit --version
        run: cargo audit --version

      - name: cargo audit
        run: |
          cargo audit --ignore RUSTSEC-2024-0336 \
                      --ignore RUSTSEC-2021-0127 \
                      --ignore RUSTSEC-2024-0370 \
                      --ignore RUSTSEC-2022-0080 \
                      --ignore RUSTSEC-2022-0061 \
                      --ignore RUSTSEC-2020-0168 \
                      --ignore RUSTSEC-2024-0384 \
                      --ignore RUSTSEC-2024-0388 \
                      --ignore RUSTSEC-2024-0421
