name: cargo audit
on:
  workflow_dispatch:

jobs:
  create-mainnet-clone:
    runs-on: [self-hosted, type-ccx43]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: hel1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build and install baedeker
        run: |
          git clone https://github.com/UniqueNetwork/baedeker.git /tmp/baedeker
          cd /tmp/baedeker
          cargo build --release
          sudo cp ./target/release/baedeker /usr/local/bin
          sudo chmod +x /usr/local/bin/baedeker
          baedeker version || true

      - name: Run baedeker
        run: |
          git clone https://github.com/opentensor/baedeker-for-subtensor.git /tmp/baedeker-for-subtensor
          cd /tmp/baedeker-for-subtensor
          ./up.sh ./forkless-data.jsonnet --tla-str=forked_spec=subtensor --tla-str=fork_source=wss://archive.chain.opentensor.ai --corrupted-storage-strategy use-default

      - name: Upload subtensor.json to S3
        run: |
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          aws s3 cp /tmp/baedeker-for-subtensor/.bdk-env/specs/subtensor.json \
            s3://subtensor/subtensor-${TIMESTAMP}.json \
            --endpoint-url https://hel1.your-objectstorage.com