name: cargo audit
on:
  workflow_dispatch:

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

#      - name: Cache baedeker build
#        uses: actions/cache@v4
#        with:
#          path: baedeker/target
#          key: baedeker-${{ runner.os }}-${{ hashFiles('baedeker/Cargo.lock') }}
#          restore-keys: baedeker-${{ runner.os }}-

      - name: Build and install baedeker
        run: |
          git clone https://github.com/UniqueNetwork/baedeker.git /tmp/baedeker
          cd /tmp/baedeker
          cargo build --release
          sudo cp ./target/release/baedeker /usr/local/bin
          sudo chmod +x /usr/local/bin/baedeker
          baedeker version || true

      - name: Run baedeker
        run: |
          git clone https://github.com/opentensor/baedeker-for-subtensor.git /tmp/baedeker-for-subtensor
          cd /tmp/baedeker-for-subtensor
          ./up.sh ./forkless-data.jsonnet --tla-str=forked_spec=subtensor --tla-str=fork_source=wss://archive.chain.opentensor.ai --corrupted-storage-strategy use-default

#      - name: Create timestamped file
#        run: |
#          TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
#          FILENAME="output_${TIMESTAMP}.txt"
#          echo "File created at $(date)" > "$FILENAME"
#          echo "Created file: $FILENAME"
#          cat "$FILENAME"