name: Label Triggers

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened

permissions:
  issues: write
  pull-requests: write
  actions: write

jobs:
  comment_on_breaking_change:
    runs-on: ubuntu-latest
    steps:
      - name: Check if 'breaking change' label is added
        if: github.event.label.name == 'breaking-change'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '@opentensor/cerebrum / @opentensor/gyrus / @opentensor/cortex breaking change detected! Please prepare accordingly!'
            })

  re_dispatch_benchmarks:
    runs-on: ubuntu-latest
    if: >
      github.event.label.name == 'skip-validate-benchmarks' ||
      github.event.label.name == 'skip-validate-benchmarks' && github.event.action == 'labeled' ||
      github.event.label.name == 'skip-validate-benchmarks' && github.event.action == 'unlabeled'
    steps:
      - name: Re-dispatch Validate-Benchmarks
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'run-benchmarks.yml',
              ref: context.payload.pull_request.head.ref
            })