[package]
name = "subtensor-macros"
version = "0.1.0"
edition = "2024"
license = "MIT"

description = "support macros for Subtensor"
repository = "https://github.com/opentensor/subtensor"
homepage = "https://bittensor.com/"

[lib]
proc-macro = true

[dependencies]
syn.workspace = true
proc-macro2.workspace = true
quote.workspace = true
ahash = { workspace = true }

[lints]
workspace = true
